server:
  port: 8080

spring:
  application:
    name: paasta-web-ide
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://PAASTA-WEBIDE-DATASOURCE/webide
    username: PAASTA-WEBIDE-DATASOURCE-USERNAME
    password: PAASTA-WEBIDE-DATASOURCE-PASSWORD
  jpa:
    hibernate:
      ddl-auto: none
      database: mysql
      show-sql: true

logging:
  level:
    ROOT:
      org:
        openpaas:
          servicebroker:
            controller: INFO


webide:
  servers:
    - XXX.XXX.XXX.XXX
    - XXX.XXX.XXX.XXX


serviceDefinition:
  id: YOUR_PLAN_ID #ex)af86588c-6212-11e7-907b-b6006ad3dp22
  name: webide
  desc: "A paasta source control service for application development.provision parameters : parameters {owner : owner}"
  bindable: false
  planupdatable: false
  plan1:
    id: YOUR_PLAN_ID1 #ex)a5930564-6212-11e7-907b-b6006ad3dps1
    name: webide-shared                #플랜
    desc: "This is a shared service plan. All services are created equally."
    type: A
  plan2:
   id: YOUR_PLAN_ID2 #ex)a5930564-6212-11e7-907b-b6006ad3dps2
   name: webide-dedicated
   desc: "This is a dedicated service plan. All services are created equally."
   type: B
